### ISSUE TITLE
Update content to new erlangpl version

### ISSUE THREAD

**Issue by baransu** [erlanglab/erlanglab.github.io#1]
Because we have new UI live and as part of 0.4 we should update images. Is there anything else you want to update @michalslaski ?

**Comment by michalslaski** [comment]
In /dashboard/system there is 'proces limit', but should be 'process limit'. I don't have any other comments right now.

**Comment by baransu** [comment]
Fixed in https://github.com/erlanglab/erlangpl-ui/pull/23/commits/a586b742eda4f36172d6be9000eed84619d951b1

**Comment by baransu** [comment]
Closed in: https://github.com/erlanglab/erlanglab.github.io/commit/88a03e5ace7ed9f4f3792fb3beea700f0b9a17ec

**Comment by michalslaski** [comment]
Text also needs updating and we should add a new picture with message passing.

**Comment by baransu** [comment]
I'll try to come up with something for that

**Comment by michalslaski** [comment]
I'm working on improving the message passing view, so we may want wait a few days with posting new pictures, but the description of the supervision tree picture needs changing.

**Comment by baransu** [comment]
@michalslaski If you can find some time please write better `Supervision tree` section 🙂

**Comment by michalslaski** [comment]
Thanks for editing the front page. We can always try to improve the readability and grammar of the text, but I think we have addressed majority of HN comments now.

**Comment by michalslaski** [comment]
Thanks for editing the front page. We can always try to improve the readability and grammar of the text, but I think we have addressed majority of HN comments now.
